### ISSUE TITLE
The external TestSupported function should, at the very least return true only for when the game is cyberpunk_2077, and false otherwise.

### ISSUE THREAD

**Issue by E1337Kat** [E1337Kat/cyberpunk2077_ext_redux#112]
This should at the very least test the game_id is the game we want.

_Originally posted by @E1337Kat in https://github.com/E1337Kat/cyberpunk2077_ext_redux/pull/102#discussion_r839666047_

**Comment by E1337Kat** [comment]
All extension's installers are checked against, I believe, so you could in theory write an extension that has a generalized installer for games that might share the same thing (like FOMOD), and so we only want to handle cyberpunk mods. Otherwise people playing other games that also have this extension installed might have weird issues.

**Comment by E1337Kat** [comment]
After reviewing #103, I think this might actually be fine as is? The wrapped testSupported seems to handle it. Still gonna leave this open until sure.

**Comment by effs** [comment]
Yep, it's checked in the wrapper! Works for both internal pipeline and individual installers.
