### ISSUE TITLE
Support CET Mods

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#13]
If a CET mod doesn't adhere to conventions, either reject it or fix it the rest of the way.

Need to at least:

- [ ] Ensure it's [bin/../]somename/init.lua so that we can correctly put it in the CET folder
- [ ] Allow init.lua in subfolders of the mod

Optional, maybe later:

- [ ] Allow mod to just have the mod at top level, and place it in CET/mods/MODNAME/

**Comment by E1337Kat** [comment]
It seems we can get the name of the archive being installed in the install function., which for CET mods should be good. I think though Yamashi is good about getting people to use conventions so it generally is fine... but just in case
