### ISSUE TITLE
CET/AMM Not Recognized (Cyber Noir Flat)

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#141]
Looks like an issue recognizing an AMM build (plus archives)

Status: can be installed w/ prompt

Mod: [Cyber Noir Flat](https://www.nexusmods.com/cyberpunk2077/mods/4193?tab=files)

![image](https://user-images.githubusercontent.com/13802421/162524967-f8f1148f-9f4d-417d-8bd9-48393bd05b45.png)

Related to #56

**Comment by E1337Kat** [comment]
Cyber Noir Flat does not install correctly on 0.6.0-gonk. Installed all to the archive folder. Is it even possible to install this flat packed mod? with a JSON file, Archive file, and lua file, in no apparent order, maybe it would be good to recommend manual install
