### ISSUE TITLE
Always First Equip installation triggers Fallback Installer

### ISSUE THREAD

**Issue by Darkenend** [E1337Kat/cyberpunk2077_ext_redux#163]
**Describe the bug**
The mod [Always First Equip](https://www.nexusmods.com/cyberpunk2077/mods/2557), reaches the Fall Back installer despite being a valid mod.

**To Reproduce**
1. Download the mod.
2. Install the mod
3. Fallback Installer should come up

**Expected behavior**
It should be a normal installation

**Screenshots**
![image](https://user-images.githubusercontent.com/34766606/172601785-ec67caee-7660-4dff-b570-e009505c1c13.png)

**Environment (please complete the following information):**
 - OS: Windows 10 19044
 - Mod: [Always First Equip](https://www.nexusmods.com/cyberpunk2077/mods/2557)
 - Extension Version: 0.6.0

**Comment by Bladehawke** [comment]
This is a known issue and is due to the new r6/input/AlwaysFirstEquip.xml.  Referenced in #162

**Comment by effs** [comment]
Thanks for the report! I'll close this one, we'll track it in #162 as a more general issue :)
