### ISSUE TITLE
ACU Presets Changed To Separate F/M Dirs

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#178]
[Appearance Change Unlocker's new version](https://www.nexusmods.com/cyberpunk2077/mods/3850?tab=files) makes has separate subdirs for male and female presets.

- [x] support using the correct dirs canonically
- [x] (maybe) support in toplevel

**Comment by E1337Kat** [comment]
Like see if the player gender is defined in the LocKey in the preset, and place into the correct folder? I assume the preset structure itself is not different. Just the folders.

**Comment by effs** [comment]
> Like see if the player gender is defined in the LocKey in the preset, and place into the correct folder? I assume the preset structure itself is not different. Just the folders.

Yeah. Either a disabled or missing value for the fun bits or facial hair could be a clue.

But thus far no idea how to even parse the LocKey…

**Comment by E1337Kat** [comment]
Don't LocKeys correlate to like something in the tweak database? Could you find it through wolvenkit or something? Perhaps also a custom modification of the mod could give some insight, like if the mod saves the preset with a string of the field it represents next to it. I didn't delve too deep into the source code, so I am not sure how doable that is.

**Comment by E1337Kat** [comment]
Ok, after looking into it a bit, I think I could modify the source a little bit to have it save the preset so it has the LocKey and the localized name so that we can know what we are looking at.

**Comment by effs** [comment]
Seb dug up some of the hashes, and `14444638123505366956` corresponds to b**bies. This should be a differentiator but need to find a Vince preset to test it..

**Comment by effs** [comment]
But yeah longer term that sounds like a much better idea :)
