### ISSUE TITLE
Support REDmod installs through vortex

### ISSUE THREAD

**Issue by E1337Kat** [E1337Kat/cyberpunk2077_ext_redux#199]
**Is your feature request related to a problem? Please describe.**
Update 1.6 adds support for REDmod,  the new official mod platform thing for CP2077

**Describe the solution you'd like**
Since the folder is different from current known folder, this will need to be created if not already and place files there as expected.

**Describe alternatives you've considered**
No alternatives available

**Additional context**
[REDmodding tools page.](https://www.cyberpunk.net/en/modding-support)
[Official 1.6 update notes](https://www.cyberpunk.net/en/news/45280/edgerunners-update-patch-1-6-list-of-changes). Info on redmodding is at the bottom

**Comment by effs** [comment]
We also need to add the `-modded` launch flag.

**Comment by Happybara24** [comment]
Nexus Mods general notes:

- This Cyberpunk game will be updated (possibly to v1.6) which will include compatibility with both legacy and new REDmod content.
- REDLauncher is an optional DLC available on all platforms (Epic/GOG/Steam) which will allow users to load the new REDmod format of mods.
- There are two components, REDManager (a user-friendly GUI) and REDmod (a Command Line application used for applying/removing the mods)
- REDmod content will be installed in a new "Mods" folder in the root game directory.
- Each mod will have its own subfolder. The top level of each subfolder will have an info.json file to identify the mod.
- REDmod content will need to be "merged" and "deployed" before it will be loaded by the game. This is handled by REDmod CLI.
To enable REDmod content, the Cyberpunk2077.exe file needs to be launched with the argument -modded.        
It is possible to set a load order for these mods using a CLI argument. redmod deploy -root="C:\Gog\Cyberpunk 2077" -mod=modB,modA,modC

[All-in-One_15913_.zip](https://github.com/E1337Kat/cyberpunk2077_ext_redux/files/9504444/All-in-One_15913_.zip)
