### ISSUE TITLE
Enable Launching The Game With REDmod Mods

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#204]
- [ ] Need to pass in the `-modded` launch parameter.

- [ ] May also require generating a dummy load order (just use alpha) until #205

**Comment by effs** [comment]
GOG and Steam handle this in their launchers so it's possible we don't need to (or shouldn't) do anything for them. Need ta test though.

**Comment by effs** [comment]
We still missing something for this one?

**Comment by E1337Kat** [comment]
I am not sure. There is conflicting information (or I am just unable to comprehend the information) regarding what determines if the game starts modded or not, if REDmod is needed or not, or whatever else.

**Comment by effs** [comment]
I'll give this one a go and see if things work as expected
