### ISSUE TITLE
Automatically Convert Old Mods to REDmods

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#207]
¿Por qué no?

Should be easy enough, no?

- Non-canonical archive mods can't be converted (pending selection UI work at least)

- Mods that contain archives and something else like a CET part can either be excluded, or split into two parts (may look weird in the game dir, but overall better?)

Additionally:

closes #196 

- [ ] Any regular Archive mod that would be installed normally moved to canonical REDmod location
  - [ ] Also install stuff that may not be valid, show warning as usual (may need new copy?)
- [ ] Any extra Archive use converted also
- [x] info.json generated
  - [x] reasonable(?) 'mod name' for the mods that don't have one, incl. path (maybe something better than current fake name)
  - [x] I guess just better parsing of mod info
  - [x] version generated with build tag `+V2077RED` (no precedence implication) ~~something like `v2077-redmod` pre-release tag so it's still SemVer~~
- [x] Notification shown for every autoconverted mod

- [ ] mod type set to REDmodArchive (or whatever)
- [ ] mod attribute set to indicate autoconvert?

- [ ] Setting or something to let user control whether to enable this or not?
  - [ ] This requires reinstalling things, doesn't it? I guess that'll be manual for now - warn about it

- [x] Trivial feature flag implementation in features.ts, the flag set is passed to installers
- [x] Support overriding in individual examples
dification.)

**Comment by E1337Kat** [comment]
While it probably would be easy enough, maybe we shouldn't modify modder's work without their consent like how spawn0 does with that tool of his. Providing a third party tool that a modder can use or a mod user can use to auto convert an old archive mod to a redmod might be doable, though. I am not sure what all needs to be in the info.json for a redmod archive type mod though.

**Comment by effs** [comment]
We already modify mods?
