### ISSUE TITLE
Support cybercmd?

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#215]
What is it? I dunno! Something related to Redscript and REDmod. But might be necessary eventually.

https://github.com/jac3km4/cybercmd

**Comment by E1337Kat** [comment]
Support Cybercmd (was just going to make this ticket lol)

Probably can do similar to what is done in #214 but with a dialogue for cyberCMD if there are redscripts and redmods.

**Comment by effs** [comment]
cybercmd can be enabled whether or not `-modded` is being used.

**Comment by effs** [comment]
Verified working in 0.8.2
