### ISSUE TITLE
Support full path REDmod mods

### ISSUE THREAD

**Issue by E1337Kat** [E1337Kat/cyberpunk2077_ext_redux#220]
**Is your feature request related to a problem? Please describe.**
When a mod has the zip file from Nexus or otherwise with `mods/[mod_name]/info.json9+other_files]`, we need to install it as expected and not complain that we don't know of this mythical creature.

**Describe the solution you'd like**
Just install the mod

**Additional context**
![image.png](https://media.discordapp.net/attachments/946698855976681473/1019435272724824094/unknown.png)

**Comment by effs** [comment]
Fixed in #223
