### ISSUE TITLE
Handling REDenabled Status and Load Order

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#231]
Just copying this here so I don't forget, TBCleared up

... :thinkauska:  the enable/disable REDmodding feature might be something to worry about after all

If we externalize (or internalize, I guess) enable/disable to Vortex - the idea there being that everything we Vdeploy will be REDenabled - then we lose the LO for a Vdisabled REDmod, don't we?

OTOH if we don't automatically REDenable all VDeployed REDmods, then we need a UI to REDenable/REDdisable them (I assume the FLBO checkbox is VEnable)
---
One option is to just do what we planned, which is much easier but means LO must be re-set each time (unless we cache it or something.)

**Comment by E1337Kat** [comment]
The FBLO checkbox is both "VEnable" ***AND*** "REDenable". After "VDeploy" new REDmods for  the LO will be set as disabled (for both V and RED). #208 already handles the enable/disable and ensures the state is the same for both V and RED when a change is made. Also the order. It does not auto add new REDmods to the LO which is where #228 comes in.

**Comment by effs** [comment]
Hm, so does that mean that it'll stay in the LO state even when it's disabled? Lemme write out my understanding...

State/data sources:

- Vstate (all installed mods, plus their modinfo)
- Vmanifest (Venabled -> Vdeploy -> did-deploy -> Vdeployment manifest file)
- Filesystem (actual mods in game dir, i.e. Vmanifest + any manually installed)
- VLO (the LO file we create (technically also exists in Vstate))
- mods.json (REDmanifest)

(Should we just ignore manually installed stuff, or do we also show that in VLO UI? It'd be easier not to.)

LO data pipeline:

VLO UI
|> VLO.json
|> `redmod.exe deploy` command-line parameters
|> mods.json
|> read by preloader when running `-modded`

We have two enabled states, Venabled (Vstate, Vmanifest, VLO?) and REDenabled (mods.json)

If we want Venabled to be accurate (i.e. the mod list says whether game will run the mod or not, assuming `-modded`) _and_ that LO is maintained even if mod is Vdisabled (or restored once it's been Venabled again)

1. The VLO creation must be based on Vstate, not deployed mods (because Vdisabled mods won't be Vdeployed)
2. VLO.json must contain Vdisabled mods, even though they're not Vdeployed (these are filtered out in REDdeploy so that redmod.exe only gets filenames that have been Vdeployed, unless it can handle ENOENT)
3. Venable/Vdisable must have a way to also REDenable/REDdisable
4. Any REDmod that is not explicitly load-ordered thru VLO UI, i.e. basically Venable/Vdisabled w/o VLO UI or manually installed if we support that is inserted in alphabetic order _below_ all explicitly load-ordered mods

So I think that means that the full pipeline is:

LOupdate = VLO UI change || Venable/Vdisable -> refresh VLO based on Vmanifest (or disk)

LOupdate
|> VLO.json serialization
|> `redmod.exe deploy` command-line parameters
|> mods.json
|> read by preloader when running `-modded`

For the first working version we could maybe ignore the non VLO UI-ordered stuff, pretend it's not installed or tag it REDdisabled, then add on that logic too?

**Comment by effs** [comment]
I _think_ this is solved for now, but let's return to this if not..
