### ISSUE TITLE
Produce Good Help/Info/Error/Warning Messages

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#24]
Kinda vague, yes. But:

- Review the messaging facilities in the Vortex API
- See if there’s a nice way to e.g. inform the user that a mod needs manual work
- Which conditions do we want to warn/error on, in general?
- Can we easily get bug reports/issues either directly to GH or sent to us?
- …?

**Comment by E1337Kat** [comment]
The Vortex API exposes the React-component system as a whole, allowing us to build out any parts of the UI that we might need.

**Comment by effs** [comment]
Need #37 for this.

**Comment by effs** [comment]
Too vague as it is; we can produce notifications and dialogs, so rest is mostly about figuring out where and when to use them.
