### ISSUE TITLE
Support FOMOD Installers

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#3]
Verify FOMODs work, or fix :)

**Comment by E1337Kat** [comment]
FOMODs work out of the box... or should, assuming the fomod creators package the fomod correctly. Not sure if there is much we can do for fomods otherwise.

**Comment by Bladehawke** [comment]
I've begun building some FOMODs for CP2077 and can verify that XML based FOMODs work
