### ISSUE TITLE
Support Config Mods

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#30]
.json and .xml files. Only file moving, support for injecting changes e.g. with xpath tbd.

**Comment by E1337Kat** [comment]
Partially completed in #46 (JSON part)
Still need xml, or as I like to call it, the hard part.

**Comment by effs** [comment]
I think this'll do, let's split XML into a new ticket and figure out if we need to do anything more with JSON at that point.
