### ISSUE TITLE
Try to Allow Collections to Set Preferred Autoconversion Toggle

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#310]
Needs to be further assessed for viability and potential risks/corner cases, but one possibility might be to provide a Tool. The Tool could by default toggle the setting `!current` but be overridden by a parameter - this is actually necessary to be able to include the tool run in a Collection, I think.

Alternatives: just have Collections pop up an info notif instead.

**Comment by E1337Kat** [comment]
Talked a bit with the Nexus guys about this. I think we might be able to get something to help know if something is being done during a collection or not. alternatively, maybe a collection should include the version of the extension that it was created on as a part of it. Generally an extension won't have such sweeping changes, but it is certainly possible, as evidenced by how our extension works....

**Comment by effs** [comment]
wontfix
