### ISSUE TITLE
Support Foundational Enabling Mods: CET, Redscript, Red4Ext, CSVMerge (, Wolvenkit?)

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#32]
The actual mods themselves, separate tracking for the mods that use them.

**Comment by E1337Kat** [comment]
For redscript, no additional support is needed really. it does add cache files on runtime, but are only used by redscript and not read by the game. On redscript updates, it will handle the cache invalidation if needed.

For CET, I know it adds some files in the course of run time, but I am unsure what. Will need to look into this. Depending on what gets created, support for it will be adding those files to the staging location for clean uninstall.

I haven't used red4ext in my gameplay so I don't even know how it works, and wolvenkit only so far as part of csvmerge.

**Comment by E1337Kat** [comment]
Done in #63 and #68
