### ISSUE TITLE
Check Whether REDmod is Enabled in MultiType Installer

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#324]
Milestone: 0.9.5

https://github.com/E1337Kat/cyberpunk2077_ext_redux/blob/2f457e399e65cd92ff32d5d03051b0416d58e7d5/src/installer.multitype.ts#L73-L82

We probably shouldn't be installing REDmods if REDmods are not enabled.

**Comment by E1337Kat** [comment]
Maybe do it in the redmod testsupported? oh though I guess then it goes to multitype and then fallback... hmmm. /shrug
