### ISSUE TITLE
Redscript duplicate file Resolution

### ISSUE THREAD

**Issue by PhiPhiper** [E1337Kat/cyberpunk2077_ext_redux#36]
Hi, I ran into some issue when two mods brought a file with the same name. One was [Reduced Loot](https://www.nexusmods.com/cyberpunk2077/mods/2678) and the other [Ai Netrunners Enhanced](https://www.nexusmods.com/cyberpunk2077/mods/2468). I resolved this by moving their scripts into new subfolders. Could this be a resolution for such a conflict?

**Comment by effs** [comment]
Yep, since it's supported, folders sounds good.

**Comment by effs** [comment]
#45 will fix this.
