### ISSUE TITLE
Mod limit workaround?

### ISSUE THREAD

**Issue by BitGrub** [E1337Kat/cyberpunk2077_ext_redux#367]
**Describe the bug**![image](https://github.com/E1337Kat/cyberpunk2077_ext_redux/assets/20694416/8acbdb9a-e618-46a9-8f12-3ea707e9a38a)
So the command line command is apparently too long. I previously got around this by deleting tons of mods, but now It's happening after simply updating existing ones.

**To Reproduce**
1. Have over 300 mods installed (I got to about 340 before the issue started)
2. Click deploy
3. Fail instantly

**Expected behavior**
The mods should be deployed

**Screenshots**
Already provided

**Environment (please complete the following information):**
 - OS: Windows 11, 22621.1928 (22H2)
 - Mod: N/A
 - Extension Version 0.9.8

**Additional context**

**Comment by E1337Kat** [comment]
This is fixed in the pre-release now (or should be assuming nothing is wrong with the implementation). #365 is the PR that added in the fix. I just have not gotten around to issuing the actual release yet. Should be fixed in say 3 days if everything goes okay.
