### ISSUE TITLE
Add API Object Ref To Installers For Messaging And Other Shenanigans

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#37]
Since the `api` object isn’t passed into the callbacks by default, we need to wrap `install()` inside the init function so that we can pass in a reference. The `api` object is needed for e.g. user-facing messages and any modals or other ui elements we want to create.

**Comment by E1337Kat** [comment]
Is this not resolved in #42 ?

**Comment by effs** [comment]
Yes! #42 covers this.
