### ISSUE TITLE
RED4Ext mods with packaged redscript are incorrectly detected as redscript mods

### ISSUE THREAD

**Issue by flibdev** [E1337Kat/cyberpunk2077_ext_redux#373]
**Describe the bug**
RED4Ext supports plugins including redscript files that are added to the script compilation list at runtime. Currently the only major plugin using this feature is [Mod Settings](https://github.com/jackhumbert/mod_settings). It's being incorrectly detected as a redscript mod and confusing users

**To Reproduce**
1. Attempt to install [Mod Settings](https://www.nexusmods.com/cyberpunk2077/mods/4885) via Vortex
2. See warning dialog

**Expected behavior**
Should be detected as a RED4Ext mod and installed without issue.

**Screenshots**
![Vortex](https://github.com/E1337Kat/cyberpunk2077_ext_redux/assets/6767042/0566a428-97ff-44fa-982c-af5bfc5c0aad)

**Comment by E1337Kat** [comment]
mhmm, I will try to get this fixed this week. Thanks.
