### ISSUE TITLE
Support Input Loader 1.1.2

### ISSUE THREAD

**Issue by Crimento** [E1337Kat/cyberpunk2077_ext_redux#376]
Seems like file structure has changed again, can't install with latest Vortex

https://github.com/jackhumbert/cyberpunk2077-input-loader/releases/tag/v0.1.2

**Comment by zejjnt** [comment]
Still (or again?) an issue 2 months later with the latest patch.

**Comment by BitGrub** [comment]
Can confirm, anyone know a workaround? (without manually installing, I mean)

**Comment by E1337Kat** [comment]
I will get this done today, I suppose. I blame work for flooding my github notifications and making it hard to go through them.

**Comment by BitGrub** [comment]
No rush! Greatly appreciate your work 👍

**Comment by E1337Kat** [comment]
New version with support is uploaded [here](https://www.nexusmods.com/site/mods/196?tab=files) vortex should auto update the new version by end of day Monday. (We cannot control when vortex auto-updates extensions)
