### ISSUE TITLE
trouble with install

### ISSUE THREAD

**Issue by MHundredM** [E1337Kat/cyberpunk2077_ext_redux#391]
![image](https://github.com/E1337Kat/cyberpunk2077_ext_redux/assets/150633575/41bde24d-96f8-4718-af00-cf686e9008a3)
![image](https://github.com/E1337Kat/cyberpunk2077_ext_redux/assets/150633575/36faaeab-39e5-4863-8f98-ee5c11ee9ede)

**Comment by neverased** [comment]
+1

**Comment by Dragon-32** [comment]
I'm seeing this error, or a very similar one, for both of these:
ArchiveXL 1.13.0 - https://www.nexusmods.com/cyberpunk2077/mods/4198?tab=description
TweakXL 1.8.5 - https://www.nexusmods.com/cyberpunk2077/mods/4197

**Comment by vaticancameosbruv** [comment]
+1
![image](https://github.com/E1337Kat/cyberpunk2077_ext_redux/assets/168480775/d1dedc96-91fb-402c-8692-fafa905eb695)

**Comment by patschi** [comment]
Possibly the [new release 0.14.4 from 5 hours ago](https://github.com/E1337Kat/cyberpunk2077_ext_redux/releases/tag/v0.10.4) is fixing it. But not sure how long it takes Vortex to pick up the new extension version...

**Comment by Dragon-32** [comment]
Vortex just updated to 0.10.4 (according to its internal version tracker). Both Archive XL 1.13.0 and TweakXL 1.8.5 installed successfully, Thanks patschi for pointing out the new release and E1337Kat for both the update and the extension itself.

**Comment by vaticancameosbruv** [comment]
Update: They fixed it!

**Comment by E1337Kat** [comment]
Closing as fixed in https://github.com/E1337Kat/cyberpunk2077_ext_redux/commit/766f861fdddfd67de17004bcdc74aed6b2d5a2e2 (and it was Auska that got this out)
