### ISSUE TITLE
ArchieXL, TweaklXL, Input Loader

### ISSUE THREAD

**Issue by Sneeew** [E1337Kat/cyberpunk2077_ext_redux#394]
**Describe the bug**
When trying to install the mods, don't work and so a lot of mods is not usable

**To Reproduce**
Install the mod with Vortex Manager 

**Expected behavior**
To install it and my game to work with mods

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows 11
 - Mod (e.g. "More Pettable Animals")

![image_2024-07-14_195519842](https://github.com/user-attachments/assets/768aa6ca-5e56-462d-9986-7137271d4503)
![image_2024-07-14_195557050](https://github.com/user-attachments/assets/9c6763eb-65cc-43ff-a742-aae2a0618759)
![image_2024-07-14_195605660](https://github.com/user-attachments/assets/ec2b0cb0-229e-4d5d-8cb5-af0acedf6c69)

**Comment by E1337Kat** [comment]
fixed with #399
