### ISSUE TITLE
Bare JSON files in the root of the archive should be rejected

### ISSUE THREAD

**Issue by Bladehawke** [E1337Kat/cyberpunk2077_ext_redux#40]
[This mod](https://www.nexusmods.com/cyberpunk2077/mods/124) is an example of a poorly packaged JSON mod.  The game includes four JSON files, two of which are named options.json. If the path is not provided by proper structure, we should actually refuse to install.  Current behavior is that fallback support installs it to the game directory where it does nothing.

**Comment by E1337Kat** [comment]
Good idea. Should it be bare `options.json` specifically that is rejected, or any "un-pathed" `.json` file in the root of the archive?

**Comment by Bladehawke** [comment]
We _could_ provide support for putting the others into the right place, but I'm not really sure if I've seen a mod that modifies anything other than one of the `options.json` files.

**Comment by E1337Kat** [comment]
mhmm, I think that would be smart. I think there should be a way to handle this correctly. I suppose we could fake it by having a false installer that detects the bare json file in the root, and then throws a message to the user about it inside the installer for it. probably should then allow the installer to do a bare 1-to-1 archive to staging install. (The installers in vortex are installing the contents of a zip file into the staging area, not into the game itself, this does allow users to fix things in the staging area before deploying to the game)

**Comment by effs** [comment]
options.json seems a special case indeed.. for the other knowns we could put them in the right path, and anything unknown can be put in a folder (assuming we've only gotten here after checking CET, Reds etc. which handle their own jsons)
