### ISSUE TITLE
Handle mods that are in their own folder

### ISSUE THREAD

**Issue by Bladehawke** [E1337Kat/cyberpunk2077_ext_redux#41]
Probably not the right title, but... basically handle mods that are laid out like:

mod.7z
|-modname
  |-bin
  | |-x64
  |-r6
and so on....

Basically if there's a directory and no files in it, but bin, r6, engine, etc. in it

**Comment by effs** [comment]
Yeah, this is a good one.. and not straightforward with the facilities I've discovered in Vortex so far. Even if we move the `FileTree` creation into the wrapper, it'd still be nice not to have to do it for every single installer. On the other hand, with the layout logic we technically can get by with a single installer that contains a pipeline inside.. that'll allow us to maintain a lot more context. The challenge (and the point of doing it this way to begin with) is making sure the logic stays as linear as possible.

Ideas:
- Hook into zipfile decompress phase?
- Maybe there's a way to invoke a 'tool' to process the .installing contents
- Maybe we just go poke directly at the filesystem
- Burn everything down?
- Ask the user to fix the mod manually
- ...?
