### ISSUE TITLE
Figure Out What We Need/Can Use From Vortex

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#43]
Noting here because I will forget about it that IExtensionContext has not one but several kinds of persistence (we could for example store whether the user wants to have a manual step of file selection), suppressNotification might help with spurious warnings, there's functions for opening a file or dir (how?) , there's some kinds of  'known paths' that getPath() accesses, there's an event system, footer and banner settings, attributeExtractor to get some kind of data from an archive, the mod type which I'm still not entirely sure what it does, plus some external interpreter support, plus there's load order management, some kind of a preview support

**Comment by effs** [comment]
https://github.com/Nexus-Mods/Vortex/blob/2ac2799a11b6dc7c68ce0141779e1eb2331179ac/src/extensions/mod_management/util/ModHistory.ts

History has some useful event references

**Comment by E1337Kat** [comment]
The "ModType" is, I know, useful in both installers (can use modtype for the testSupported) and for the "added_files" event. The "added_files" event is especially useful as it can be used to grab logs and other files added by a mod and pull it back to the staging folder. this allows an "un-deploy" to truly remove mods from the game folder. This would be good for us for foundational mods and the CET mods, I think.

**Comment by effs** [comment]
`api.getPath()` for e.g. `"userData"`

`api.lookupModMeta()` might give us some info for manual installs. `api.saveModMeta()` saves?

`api.runExecutable()`

`api.store.getState()` or `api.getState()`

`ctx.registerModSource()`

`ctx.registerMerge()` maybe useful for non-xml merging

`ctx.registerPreview()` for some sort of diff/preview functionality.. maybe good enough for our needs?

**Comment by Pickysaurus** [comment]
If you have specific questions about this feel free to poke us on Discord or check the docs here: https://nexus-mods.github.io/vortex-api/2020/09/04/Introduction.html
