### ISSUE TITLE
Review TweakDB Support

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#6]
TweakDB is deprecated, so make sure the user knows this is the case - but support installing these 'heritage' mods.

**Comment by effs** [comment]
- [Photo Mode Unlocker 1.3](https://www.nexusmods.com/cyberpunk2077/mods/3135?tab=files) ![image](https://user-images.githubusercontent.com/13802421/158942456-7f5bcef1-d0a4-469b-92b4-57decd985af4.png)

**Comment by E1337Kat** [comment]
Maybe give a warning on it as well saying that it is deprecated and should use the TweakXL or whatever instead?

**Comment by E1337Kat** [comment]
I think that there might be only that one mod that uses TweakDB, and it is being updated for TweakXL on 1.5... so maybe just drop adding TweakDB completely since nothing will use it?

**Comment by effs** [comment]
tweakdb is no more
