### ISSUE TITLE
Support Reshade Mods

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#8]
Reshade uses INI files, too, so if we want to support them or prevent them from being miscategorized as INI mods, add some detection..

**Comment by Bladehawke** [comment]
The first problem with adding actual detection is [Vortex's own handling of files](https://github.com/Nexus-Mods/Vortex/issues/10044).  As it stands, this extension currently seems to drop INI files into the folder they are in in the archive, so a properly set up Reshade should be packaged as `bin\x64\my_awsome_reshade.ini`.  

Of course most of them aren't currently packaged that way and a lot of them are also including their old shaders from previous version in the download

**Comment by Bladehawke** [comment]
I was thinking that we could wrap this into the INI handler since we don't get access to the destination path until the install phase.

**Comment by E1337Kat** [comment]
Done in #52
