### ISSUE TITLE
Refactor Updated Installers Out Into Separate Files

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#88]
A couple installers are already starting to get close to final form, so let's move those out into separate files. Anything that is moved should get refactored to use the layout style.

As per #82 drop RedCetMix entirely
 
Refactored and moved:

- [ ] Core, CSVMerge, Wkit (not fully refactored yet)
- [ ] MultiType
- [ ] Red4Ext
- [ ] Redscript
- [ ] ArchiveOnly
- [ ] CET
- [ ] JSON
- [ ] INI
- [ ] Reshade
- [ ] Fallback
- ...

**Comment by Bladehawke** [comment]
Do we want to remove the CSVMerge (and WKit CII which was added because it's a dependency ) now that CSVMerge has been deprecated by AchiveXL?

**Comment by effs** [comment]
> Do we want to remove the CSVMerge (and WKit CII which was added because it's a dependency ) now that CSVMerge has been deprecated by AchiveXL?

Yep I think so, my understanding is that the maintainers don't want anyone using CSVMerge anymore so we don't need to support it (but ofc could pop up a warning instead).
