### ISSUE TITLE
Base Logic Around Single Mod Type Per Mod

### ISSUE THREAD

**Issue by effs** [E1337Kat/cyberpunk2077_ext_redux#9]
(Just a memo rather than a TODO in code..)

Rather than go through all types and possible conflicting heuristics, try to figure out which type of mod it is and only apply specific logic to avoid possible misplacement of files.

E.g. CET mod can contain .archive files, but Archive mods can't contain lua files, or Red4ext mods can contain .ini files, but INI mods can't have red4ext stuff.

**Comment by E1337Kat** [comment]
- [ ] Support basic only archive installer
- [ ] Support CET mod (including included archives, like the Metro mod does)
- [ ] Support Redscript mods (including when some might have lua files
- [ ] Support reshade presets
- [ ] Support ini mods
- [ ] Support others??? not sure what other mod types there are.

**Comment by effs** [comment]
Think we're good here, the logic works now, just need to add the missing types (tracked in the milestone)
